- name: Remove local mysql database
  delegate_to: localhost
  shell: >
    mysql \
      -u {{ db_pull_local_database_user }} \
      --password={{ db_pull_local_database_password }} \
      -h {{ db_pull_local_database_host }} \
      -e "DROP DATABASE IF EXISTS {{ db_pull_local_database_name }};"